# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(default='swdefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
