# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0005_auto_20170419_0624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortURLManager',
        ),
    ]
