# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import shorterner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shorterner', '0006_delete_shorturlmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=220, validators=[shorterner.validators.validate_url, shorterner.validators.validate_url_with_com]),
        ),
    ]
